### ISSUE TITLE
Train student on the Wiki.js

### ISSUE THREAD

**Issue by head-iie-vnr** [Vignana-Jyothi/webx#13]

**Comment by bVedasi** [comment]
![image29](https://github.com/Vignana-Jyothi/webx/assets/166896063/22148014-c988-44af-9267-7d878deebd4e)
![image30](https://github.com/Vignana-Jyothi/webx/assets/166896063/c0ff3760-5364-45f0-a836-0411af708dc7)
Developed home page

**Comment by bVedasi** [comment]
![image25](https://github.com/Vignana-Jyothi/webx/assets/166896063/c51d5a17-bb6d-471f-909b-6efaac0b64d9)
![image36](https://github.com/Vignana-Jyothi/webx/assets/166896063/e9764cf4-22fb-4289-a7ba-2015f10ccd5a)
![image58](https://github.com/Vignana-Jyothi/webx/assets/166896063/09ae9e56-4d73-42c9-9d83-f8e212162351)
Developed codelab page

**Comment by bVedasi** [comment]
![image31](https://github.com/Vignana-Jyothi/webx/assets/166896063/f18dc03f-3feb-4f4c-95a4-f2eebcdc7f0f)
![image9](https://github.com/Vignana-Jyothi/webx/assets/166896063/63d0a04b-9166-49ea-a2a3-d09ae6f5713a)
![image39](https://github.com/Vignana-Jyothi/webx/assets/166896063/1a88343d-8a53-4d39-9a45-5220b0454bfe)
![image8](https://github.com/Vignana-Jyothi/webx/assets/166896063/ed4cf88c-71a9-48ea-b26d-4aba9916200d)
![image21](https://github.com/Vignana-Jyothi/webx/assets/166896063/d5442610-5faf-4dae-b5b8-0bea49023a86)
Developed ACM page

**Comment by bVedasi** [comment]
![image22](https://github.com/Vignana-Jyothi/webx/assets/166896063/1dd83b38-3422-4fd2-93b4-a2f9feb2e0f5)
Developed tab page (using markdown)

**Comment by DEV-0912** [comment]
![image](https://github.com/Vignana-Jyothi/webx/assets/169129783/c7537a98-7b07-4789-88ef-400781754193)
in the data base we had field called pages there its storing the data

**Comment by bVedasi** [comment]
![image](https://github.com/Vignana-Jyothi/webx/assets/166896063/fe1cfd74-faef-4685-9815-a05ff8ab0e9f)
Home page is added to the data base. Likewise, all other pages are going into the data base.

**Comment by bVedasi** [comment]
![image71](https://github.com/Vignana-Jyothi/webx/assets/166896063/ad893899-1e8b-4f9d-a644-169579eaacb8)
![image53](https://github.com/Vignana-Jyothi/webx/assets/166896063/22d665f3-bb6d-4d76-9441-a52d586bbf60)
![image40](https://github.com/Vignana-Jyothi/webx/assets/166896063/8f155b72-4087-42da-81ba-83419a6f805b)
![image67](https://github.com/Vignana-Jyothi/webx/assets/166896063/93961ea9-75ff-42f0-8246-e0bb758f90bc)
![image4](https://github.com/Vignana-Jyothi/webx/assets/166896063/7c971b59-007a-41bb-8b13-bcae68dad373)
Developed ASME page

**Comment by bVedasi** [comment]
![image41](https://github.com/Vignana-Jyothi/webx/assets/166896063/660390ce-9474-4513-918c-43fb417284b6)
![image60](https://github.com/Vignana-Jyothi/webx/assets/166896063/7324843c-7c3b-488a-bc1d-8bbc5d1efa13)
![image24](https://github.com/Vignana-Jyothi/webx/assets/166896063/f418fb96-6c81-4154-b79d-19fd9df8cd71)
![image44](https://github.com/Vignana-Jyothi/webx/assets/166896063/43455a9d-74fe-4cce-9511-552697e5c254)
![image73](https://github.com/Vignana-Jyothi/webx/assets/166896063/3dd7cfa4-8dfa-4641-b4be-655cac2bb00e)
Developed CSI page

**Comment by bVedasi** [comment]
![image1](https://github.com/Vignana-Jyothi/webx/assets/166896063/715233d4-81e8-4c69-86fd-9a0cf0d29ab1)
![image7](https://github.com/Vignana-Jyothi/webx/assets/166896063/0ae0e18a-4104-4634-9fd6-db5894cdd894)
![image39](https://github.com/Vignana-Jyothi/webx/assets/166896063/d17adec2-e571-4085-a1ef-76e0372a3a7e)
![image26](https://github.com/Vignana-Jyothi/webx/assets/166896063/358fcc76-87c4-4db5-a4bf-c736915c2786)
Developed VNR journalism page

**Comment by bVedasi** [comment]
![image69](https://github.com/Vignana-Jyothi/webx/assets/166896063/371eae78-2818-4860-95a4-f7ba29711f33)
![image70](https://github.com/Vignana-Jyothi/webx/assets/166896063/b02e9714-1a51-4349-8095-f38937cc1034)
![image68](https://github.com/Vignana-Jyothi/webx/assets/166896063/680f8457-6184-478c-95db-0bc966262fa5)
![image38](https://github.com/Vignana-Jyothi/webx/assets/166896063/c4566f4f-fc29-4bc8-ac76-3e866d9cbded)
Developed ED Cell page

**Comment by bVedasi** [comment]
![image75](https://github.com/Vignana-Jyothi/webx/assets/166896063/ea792d43-6ab4-4777-bab8-e787331192c0)
![image51](https://github.com/Vignana-Jyothi/webx/assets/166896063/be155a88-a12a-42a1-913c-b36ff824ef1f)
![image56](https://github.com/Vignana-Jyothi/webx/assets/166896063/bd280de8-16a9-44a8-beb9-a0d36c52e80b)
![image15](https://github.com/Vignana-Jyothi/webx/assets/166896063/98bd893a-d478-4ac2-9f30-19b3d882cc10)
Developed GDSC page

**Comment by bVedasi** [comment]
![image16](https://github.com/Vignana-Jyothi/webx/assets/166896063/1fb8fe6c-0437-4d06-8f3d-aea7163cd18e)
![image18](https://github.com/Vignana-Jyothi/webx/assets/166896063/eed81a93-b8e9-4f1f-80a1-468a95e2b19d)
![image6](https://github.com/Vignana-Jyothi/webx/assets/166896063/02444cd5-59bb-4433-a0fa-15c06c95d24f)
![image2](https://github.com/Vignana-Jyothi/webx/assets/166896063/67e612a2-7c52-479f-b909-8358e1183e0e)
Developed IEEE page

**Comment by bVedasi** [comment]
![image50](https://github.com/Vignana-Jyothi/webx/assets/166896063/a99e3ce8-e5a9-4cc6-843f-8ffb8c5d8034)
![image27](https://github.com/Vignana-Jyothi/webx/assets/166896063/cf9f5b7e-e609-4c7e-8b8c-fa7d88d9f0e1)
![image3](https://github.com/Vignana-Jyothi/webx/assets/166896063/cafcc416-ccce-4db8-b6e0-cc3a70d56df6)
![image65](https://github.com/Vignana-Jyothi/webx/assets/166896063/4168ee69-77cc-42df-b365-62c8e83cd3ff)
Developed IEI page

**Comment by bVedasi** [comment]
![image61](https://github.com/Vignana-Jyothi/webx/assets/166896063/a1057041-11ba-4f59-968a-48abc2345fae)
![image42](https://github.com/Vignana-Jyothi/webx/assets/166896063/71df59a8-1142-4d64-b2cf-77023310f25c)
![image33](https://github.com/Vignana-Jyothi/webx/assets/166896063/87c9b59b-4389-4ee1-9db9-2a521a01e37c)
![image45](https://github.com/Vignana-Jyothi/webx/assets/166896063/615676f3-dc05-40ed-b45a-abdc19fc9072)
Developed IETE page

**Comment by bVedasi** [comment]
![image35](https://github.com/Vignana-Jyothi/webx/assets/166896063/cc000794-a72f-439a-80e0-c034e2188dc4)
![image74](https://github.com/Vignana-Jyothi/webx/assets/166896063/ab585531-d6ba-48ae-a92a-08b6885abc91)
![image47](https://github.com/Vignana-Jyothi/webx/assets/166896063/423aa87f-fcc9-4c80-b2db-fba68cc893d1)
![image63](https://github.com/Vignana-Jyothi/webx/assets/166896063/78e372fe-ad5c-4e34-88c1-f8a386aeb429)
Developed ISOI page

**Comment by bVedasi** [comment]
![image64](https://github.com/Vignana-Jyothi/webx/assets/166896063/93c761f7-5359-4533-afd0-deb70109cbc9)
![image52](https://github.com/Vignana-Jyothi/webx/assets/166896063/07fa5950-9332-44a8-88f0-bd030e7861bf)
![image55](https://github.com/Vignana-Jyothi/webx/assets/166896063/cdd77ef9-a958-4e01-ae29-f110d82fa3e4)
![image23](https://github.com/Vignana-Jyothi/webx/assets/166896063/dec155f0-dd70-4499-949d-0af8e1691d05)
Developed ISTE page

**Comment by bVedasi** [comment]
![image34](https://github.com/Vignana-Jyothi/webx/assets/166896063/d71dda1f-008f-4bfd-8c4e-5525ba502c37)
![image37](https://github.com/Vignana-Jyothi/webx/assets/166896063/41d16b09-ca3b-4eb8-b7d3-24b94ce14738)
![image32](https://github.com/Vignana-Jyothi/webx/assets/166896063/4d0da49d-eae0-4fcd-b0f4-6f2d4184bd7f)
![image57](https://github.com/Vignana-Jyothi/webx/assets/166896063/6ec344af-b8b8-442b-925b-84efd1a4ccef)
Developed NSS page

**Comment by bVedasi** [comment]
![image13](https://github.com/Vignana-Jyothi/webx/assets/166896063/047d90da-d211-4576-b38b-ea1a074fed75)
![image19](https://github.com/Vignana-Jyothi/webx/assets/166896063/6fae42ac-1e2e-4e4c-928c-8229291a6a92)
![image43](https://github.com/Vignana-Jyothi/webx/assets/166896063/36b56f16-5bf6-48e6-ba54-05f85f5d3006)
![image5](https://github.com/Vignana-Jyothi/webx/assets/166896063/cf1804fc-8944-4d6f-a331-45d4bd7254e4)
Developed SAE page

**Comment by head-iie-vnr** [comment]
Thanks for doing this @bVedasi 

Few Questions 

- Can we make the left side navigation bar hierarchical 
- If I deploy Wiki.js on another server (machine), can we move all the content to that server easily ? 
- Is there anything that is part of the Wiki.js which are stored as files on your machine?


cc: @tarakakiranmayi @DEV-0912

**Comment by sahiithiii** [comment]
![Screenshot 2024-05-31 093046](https://github.com/Vignana-Jyothi/webx/assets/168961311/292918db-dbf7-4c48-b320-7242aff8ae3a)

**Comment by sahiithiii** [comment]
![Screenshot 2024-05-31 093108](https://github.com/Vignana-Jyothi/webx/assets/168961311/e81008f6-d691-4313-bce4-47577c6e8d6e)

**Comment by sahiithiii** [comment]
![image](https://github.com/Vignana-Jyothi/webx/assets/168961311/b7f0a34a-9f7b-4442-8c52-4588983ddb25)

**Comment by sahiithiii** [comment]
![Screenshot 2024-05-31 093155](https://github.com/Vignana-Jyothi/webx/assets/168961311/c83aa1a6-98ae-4b43-991b-24cebb55711c)

**Comment by sahiithiii** [comment]
![Screenshot 2024-05-31 093213](https://github.com/Vignana-Jyothi/webx/assets/168961311/c22c8287-80e6-4bd2-a944-0d95bbbe8127)
![Screenshot 2024-05-31 093225](https://github.com/Vignana-Jyothi/webx/assets/168961311/80d8215f-4b99-48a7-a1b2-c1ce7b593a42)
![Screenshot 2024-05-31 093236](https://github.com/Vignana-Jyothi/webx/assets/168961311/24c00fa3-427a-4d52-8191-b87c2640dd02)
![Screenshot 2024-05-31 093257](https://github.com/Vignana-Jyothi/webx/assets/168961311/9ec77c4b-f422-481a-9b6d-aeb7b593397a)
![Screenshot 2024-05-31 093310](https://github.com/Vignana-Jyothi/webx/assets/168961311/1a8e2454-1347-4bf3-ad05-53e27957940b)
![Screenshot 2024-05-31 093320](https://github.com/Vignana-Jyothi/webx/assets/168961311/6d22efe0-d44f-4011-9726-220ba233f6f5)
![Screenshot 2024-05-31 093337](https://github.com/Vignana-Jyothi/webx/assets/168961311/b4e8dfb1-15c5-4bdd-a613-907f0e98a98f)

**Comment by sahiithiii** [comment]
![Screenshot 2024-05-31 201301](https://github.com/Vignana-Jyothi/webx/assets/168961311/466611bc-9982-4ed9-8355-7218b62b235f)
![Screenshot 2024-05-31 201559](https://github.com/Vignana-Jyothi/webx/assets/168961311/054dfd76-66cf-4582-948b-834648aafd24)
![Screenshot 2024-05-31 201609](https://github.com/Vignana-Jyothi/webx/assets/168961311/f900ceb7-1238-454c-9a80-b34220bb7951)
![Screenshot 2024-05-31 201620](https://github.com/Vignana-Jyothi/webx/assets/168961311/6a850dc7-4528-4f45-998d-e24f956166a0)
![Screenshot 2024-05-31 201632](https://github.com/Vignana-Jyothi/webx/assets/168961311/468148fa-a03f-4329-9bb0-896bc269f489)
![Screenshot 2024-05-31 201846](https://github.com/Vignana-Jyothi/webx/assets/168961311/5c1ba668-0b80-48fd-bdae-d7ef106885d1)
![Screenshot 2024-05-31 201822](https://github.com/Vignana-Jyothi/webx/assets/168961311/dc79b254-6665-4a55-be85-83b242b6afad)
![Screenshot 2024-05-31 201915](https://github.com/Vignana-Jyothi/webx/assets/168961311/d9854a18-3f6d-49ad-8155-504bbfef9e44)
![Screenshot 2024-05-31 201741](https://github.com/Vignana-Jyothi/webx/assets/168961311/cbd1b483-3600-4bf7-ad0d-770ea3f35e1e)
![Screenshot 2024-05-31 201750](https://github.com/Vignana-Jyothi/webx/assets/168961311/b99bd877-a211-4eeb-a351-c0249820df68)
![Screenshot 2024-05-31 201804](https://github.com/Vignana-Jyothi/webx/assets/168961311/95fd513a-c5d9-45a8-a99e-0bdf6e66f993)
![Screenshot 2024-05-31 201837](https://github.com/Vignana-Jyothi/webx/assets/168961311/c4f1a200-eed4-43ad-bdd2-6fb04e89906c)
![Screenshot 2024-05-31 201822](https://github.com/Vignana-Jyothi/webx/assets/168961311/f1803ae7-74b0-499b-ba8c-b972c1a8f445)

**Comment by sahiithiii** [comment]
![Screenshot 2024-06-02 165639](https://github.com/Vignana-Jyothi/webx/assets/168961311/b6446fae-7200-4d5d-8198-9e426b186b7c)
![Screenshot 2024-06-02 165647](https://github.com/Vignana-Jyothi/webx/assets/168961311/c6cc9e2c-e3c0-4327-a6de-0647d84da412)
![Screenshot 2024-06-02 165658](https://github.com/Vignana-Jyothi/webx/assets/168961311/47c5f7d6-c45f-4b73-8800-25b077d75399)
![Screenshot 2024-06-02 165707](https://github.com/Vignana-Jyothi/webx/assets/168961311/5dfd3f88-c507-45a9-ada7-4528ccf373d1)
![Screenshot 2024-06-02 165716](https://github.com/Vignana-Jyothi/webx/assets/168961311/6a860374-2f6c-4178-a9ae-d639db2c0543)
![Screenshot 2024-06-02 165731](https://github.com/Vignana-Jyothi/webx/assets/168961311/480dc903-9f62-4e70-8601-6ee916c865bb)
![Screenshot 2024-06-02 165741](https://github.com/Vignana-Jyothi/webx/assets/168961311/9e1b098f-eade-4ab1-a11a-7e8298a404ea)
![Screenshot 2024-06-02 165751](https://github.com/Vignana-Jyothi/webx/assets/168961311/14cbbbd3-5b9d-4c5c-ba37-43d0e391763f)
![Screenshot 2024-06-02 165758](https://github.com/Vignana-Jyothi/webx/assets/168961311/efb94732-8146-4396-8454-daf756aa5cec)
![Screenshot 2024-06-02 165806](https://github.com/Vignana-Jyothi/webx/assets/168961311/a28fa60f-a393-40f9-b1f2-c1f71dd9e94d)
![Screenshot 2024-06-02 165822](https://github.com/Vignana-Jyothi/webx/assets/168961311/53564283-2851-4d24-8aee-14ed0d11f884)
![Screenshot 2024-06-02 165834](https://github.com/Vignana-Jyothi/webx/assets/168961311/e86e64b2-2262-40fa-a4b7-2f34432b6291)
![Screenshot 2024-06-02 165841](https://github.com/Vignana-Jyothi/webx/assets/168961311/456fdf6e-06dc-4ee2-a215-3a2cacf83706)
![Screenshot 2024-06-02 165851](https://github.com/Vignana-Jyothi/webx/assets/168961311/2a521a31-f1a3-431a-b207-2e7112075893)
![Screenshot 2024-06-02 165908](https://github.com/Vignana-Jyothi/webx/assets/168961311/6039a639-a21f-4bf2-a8b5-95275b884cc0)
![Screenshot 2024-06-02 165919](https://github.com/Vignana-Jyothi/webx/assets/168961311/432cb8f4-193a-484e-b715-debe34e9473c)
![Screenshot 2024-06-02 165929](https://github.com/Vignana-Jyothi/webx/assets/168961311/3b308f19-3ae2-4768-bcf8-880e9fc12ba0)
![Screenshot 2024-06-02 165940](https://github.com/Vignana-Jyothi/webx/assets/168961311/c23ea3a2-6d12-47e6-8512-b31cc5e463e9)
![Screenshot 2024-06-02 165953](https://github.com/Vignana-Jyothi/webx/assets/168961311/7d4f18d2-a848-4ff2-8c9c-d09a66d8d67c)
![Screenshot 2024-06-02 170008](https://github.com/Vignana-Jyothi/webx/assets/168961311/6e344b6f-1e84-469a-91ca-beb0fafa6a8c)
![Screenshot 2024-06-02 170016](https://github.com/Vignana-Jyothi/webx/assets/168961311/fd32989d-d86a-43e2-b56c-68015b791842)
![Screenshot 2024-06-02 170029](https://github.com/Vignana-Jyothi/webx/assets/168961311/cef06ed2-02e2-4bf8-930d-b905f18d30e6)
![Screenshot 2024-06-02 170040](https://github.com/Vignana-Jyothi/webx/assets/168961311/9d8167f9-f273-4bf4-a32d-5857d468f67e)
![Screenshot 2024-06-02 170050](https://github.com/Vignana-Jyothi/webx/assets/168961311/a1c2a934-257f-4fbf-bbc0-59a1d81929ed)
![Screenshot 2024-06-02 170101](https://github.com/Vignana-Jyothi/webx/assets/168961311/4e962f3e-9a60-42c3-893f-3b00dbde7c7c)
![Screenshot 2024-06-02 170116](https://github.com/Vignana-Jyothi/webx/assets/168961311/a66b6b93-d0fc-4d83-8032-3511a88aa562)
![Screenshot 2024-06-02 170125](https://github.com/Vignana-Jyothi/webx/assets/168961311/6246f3e1-0294-42f6-b117-603ebfb00bcf)
![Screenshot 2024-06-02 170137](https://github.com/Vignana-Jyothi/webx/assets/168961311/e51263eb-cfc9-4858-bad2-5fd2ebb8910a)
![Screenshot 2024-06-02 170144](https://github.com/Vignana-Jyothi/webx/assets/168961311/a5f81bda-a93a-429f-83ab-b2b1dc10679e)
![Screenshot 2024-06-02 170152](https://github.com/Vignana-Jyothi/webx/assets/168961311/cc5ba3fe-14f8-4e5d-9ea4-bfae24be3220)
![Screenshot 2024-06-02 170159](https://github.com/Vignana-Jyothi/webx/assets/168961311/a5386720-9dbc-4115-9807-7fe0fd2cc737)
![Screenshot 2024-06-02 170207](https://github.com/Vignana-Jyothi/webx/assets/168961311/fa07e042-6956-457a-bbc3-60f692cd77ea)
![Screenshot 2024-06-02 165731](https://github.com/Vignana-Jyothi/webx/assets/168961311/61debdea-1318-4178-b809-ae2788752d1f)
