### ISSUE TITLE
Documentation on Setup, Dos & Donts.

### ISSUE THREAD

**Issue by head-iie-vnr** [Vignana-Jyothi/webx#14]

**Comment by HarshiniBV** [comment]
**Requirements for Wiki.js:**
- mysql/mariadb/postgresql
- Apache2
- Ubuntu
- Nodejs and npm

**Comment by HarshiniBV** [comment]
**STEPS TO DOWNLOAD WIKI.JS  (In Linux) :** 

check whether you have the proper Ubuntu version installed on your server with the following command:
`lsb_release -a`

You should get this output:
`No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 22.04 LTS
Release: 22.04
Codename: jammy`

Make sure that all Ubuntu OS packages installed on the server are up to date:
`sudo apt update -y`

**Comment by HarshiniBV** [comment]
**Install NodeJS:**
`curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash -

sudo apt update

sudo apt install nodejs

node -v; npm -v`

**Comment by HarshiniBV** [comment]
**Install MariaDB and Database:**
`sudo apt install mariadb-server`

`mysql`

Once logged in to MySQL shell, we can execute the following commands.
`mysql> CREATE DATABASE wikijs;
mysql> GRANT ALL on wikijs.* to wikijs@localhost identified by 'm0d1fyth15';
mysql> FLUSH PRIVILEGES;
mysql> \q`

Create a more complicated database password, substitute m0d1fyth15 in the command above with a better and stronger one.

**Comment by HarshiniBV** [comment]
**Install Wiki.js:**
`useradd -m -d /opt/wikijs -U -r -s /bin/bash wikijs`

`su - wikijs`

`wget https://github.com/Requarks/wiki/releases/latest/download/wiki-js.tar.gz`

`tar -xzvf wiki-js.tar.gz`

`cp -a config.sample.yml config.yml`

`nano config.yml`

Find this lines in the file:
db:
  type: postgres

  # PostgreSQL / MySQL / MariaDB / MS SQL Server only:
  host: localhost
  port: 5432
  user: wikijs
  pass: wikijsrocks
  db: wiki

Change the database type ‘postgres’ with ‘mariadb’, also use port 3306 instead of 5432. The lines should look like this:
db:
  type: mariadb

  # PostgreSQL / MySQL / MariaDB / MS SQL Server only:
  host: localhost
  port: 3306
  user: wikijs
  pass: m0d1fyth15
  db: wikijs

Save the file then exit from the editor. You can also exit from user ‘wikijs’ and back to your root or sudo user.

**Comment by HarshiniBV** [comment]
**Create Systemd File:**
`nano /etc/systemd/system/wikijs.service`

Insert the following into the file:

Unit]
Description=Wiki.js
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/node server
Restart=always

User=wikijs
Environment=NODE_ENV=production
WorkingDirectory=/opt/wikijs

[Install]
WantedBy=multi-user.target

Save the file, exit, and reload the systemd daemon.

`systemctl daemon-reload`

`systemctl enable --now wikijs`

**Comment by HarshiniBV** [comment]
**Installing Apache2:**
`sudo apt update`

`sudo apt install apache2 libapache2-mod-proxy-html libxml2-dev`

`sudo a2enmod proxy proxy_http rewrite proxy_html`

`sudo nano /etc/apache2/sites-available/wikijs.conf`

(Insert the following configuration )
            <VirtualHost *:80>
                  ServerName wiki.example.com
                  ProxyPass / http://localhost:3000/
                  ProxyPassReverse / http://localhost:3000/
            </VirtualHost>
(Save and exit after typing this)

`sudo a2ensite wikijs.conf`

`sudo systemctl reload apache2`

**Comment by HarshiniBV** [comment]
Links (Installation): 
https://www.howtoforge.com/how-to-install-wikijs-on-ubuntu-22-04/
https://www.linuxcloudvps.com/blog/how-to-install-wiki-js-on-ubuntu-22-04/
For windows: https://docs.requarks.io/install/windows

**Comment by HarshiniBV** [comment]
[https://docs.google.com/document/d/1Qf1sWEXQDMWMgN1cIGNvbFvyZEjSlH07TiDxE6eJx24/edit?usp=sharing](url)

**Comment by head-iie-vnr** [comment]
Thanks for doing this @HarshiniBV 

When you get time please add details in the Issue description. 

Scope of work. 
- Prepare documentation regarding setup instructions
- Write documentation for users of the wiki.js (if possible this should be the landing page on the wiki.js)
- Add more details about donts so that content they upload in the wiki.js website is compliant with college policy. 

Acceptance criteria 
- Other new engineer should be able to follow the instructions & setup wiki.js 
-
