### ISSUE TITLE
[WifiScanner] Save the Wifi Signals. 

### ISSUE THREAD

**Issue by head-iie-vnr** [Vignana-Jyothi/webx#32]
Save the Wifi signals against the user location. 

Divide the page into 3 tabs.

### Scanner
This page should have the 'Scan Wifi' button. When clicked it should show the wifi signal list. When the wifi signal list is not empty, enable the 'Save Location' button. On SaveLocation user should be able to save the location name in 50 characters of less.

### Locations
Second tab should show all saved location. Each row should be location name. If the location name is clicked it should show the wifi signal strengths which were aready stored. Let us call this tab as 'Locations'

### Where am I
Third tab should be 'Where am I'. On this tab, on button press the current wifi signal strengths should be compared with database signal strenths. And all the location should be sorted based on the closest signal match from the detected Wifi names.

**Comment by DEV-0912** [comment]
It's better to develop an app rather than a website.

**Comment by head-iie-vnr** [comment]
It is android app.

**Comment by head-iie-vnr** [comment]
Attached screens



![WhatsApp Image 2024-06-15 at 10 49 48 PM](https://github.com/Vignana-Jyothi/webx/assets/163392003/ffb8b54b-8f93-4cdd-9f7b-3cba3bbebd17)
5 at 10 49 49 PM (2)](https://github.com/Vignana-Jyothi/webx/assets/163392003/dbd77624-2fd6-4754-b21a-84586903935e)
![WhatsApp Image 2024-06-15 at 10 49 49 PM (1)](https://github.com/Vignana-Jyothi/webx/assets/163392003/1fcd0e8a-4edc-447b-bd8d-6cff2f343546)
![WhatsApp Image 2024-06-15 at 10 49 49 PM](https://github.com/Vignana-Jyothi/webx/assets/163392003/972f46aa-c0e2-41be-a745-1b2a9b3e6386)
![WhatsApp Image 2024-06-15 at 10 49 48 PM (1)](https://github.com/Vignana-Jyothi/webx/assets/163392003/4dfee606-eb87-48b7-ad72-9c7f420c3cec)

**Comment by head-iie-vnr** [comment]
Refactored the code into separate files & minor UX changes


![WhatsApp Image 2024-06-15 at 11 13 51 PM](https://github.com/Vignana-Jyothi/webx/assets/163392003/a450006d-aa5d-4f2f-87db-67381d513552)
![WhatsApp Image 2024-06-15 at 11 13 50 PM (1)](https://github.com/Vignana-Jyothi/webx/assets/163392003/ddf8b7b6-462f-4606-89b5-6f3e8583b6e4)
![WhatsApp Image 2024-06-15 at 11 13 50 PM](https://github.com/Vignana-Jyothi/webx/assets/163392003/c52181c8-f7a3-42a1-8728-73bbcce44acf)

**Comment by head-iie-vnr** [comment]
The results are not satisfactory, so not adding screenshots. 

Closing this here.

**Comment by head-iie-vnr** [comment]
Code also was reverted back to how it was 9 hours ago.
